### ISSUE TITLE
defaults/main.yml sets ansible_become

### ISSUE THREAD

**Issue by piluxh** [redhat-sap/sap-hostagent#6]
In main.yml of the defaults for this role, the global variable ansible_become is set to true. Once can probably argue that the defaults section of any role should never change something which has effects outside of the role.

In this case, setting ansible_become to true caused all of the local_action tasks in other roles, both before and after this role, to fail. The tasks with the local_action would actually also have a "become: false", but because of ansible_become set to true, this was ignored.

This is a very serious issue as it caused errors all over the playbooks. I removed the definition of ansible_become and it still worked.

**Comment by hunter86bg** [comment]
It seems that the issue I have opened (#14 ) is a duplicate to this one.
I agree this is a bad behaviour and I hope someone merges https://github.com/redhat-sap/sap-hostagent/pull/15 so other's won't have the same issue.

In our case, it forced always become (even when we tagged only another role from the same playbook) and that's not possible on AWX/Tower.
